module.exports = {
    HARVESTER_ROOM_MAX: 6,
    BUILDER_ROOM_MAX: 2,
    GUARD_ROOM_MAX: 6,
    GUARD_ROOM_PATROL: 2,
    
    SPAWN_ENERGY_CAPACITY: 300,
    MIN_UNIT_ENERGY: 190,
    MIN_HARVESTER_COST: 250,
    MIN_BUILDER_COST: 350,
    MIN_GAURD_COST: 190
};