module.exports = {
    IDLE: -1,
    HARVEST_RESOURCE: 0,
    RESTOCK_RESOURCE: 1,
    FILL_TOWERS: 2,
    GATHER_ENERGY: 3,
    BUILD_STRUCTURE: 4,
    UPGRADE_CONTROLLER: 5,
    DELIVER_RESOURCE: 6,
    SCOUT_ROOMS: 7
};